/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asociacion.aluma;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.ImportResource;

@SpringBootApplication
@ImportResource({"classpath:config/jpa-config.xml"})
public class App {
    public static void main(String[] args) {
    	ConfigurableApplicationContext context  =
    			SpringApplication.run(App.class, args);
    	
    	context.close();
    }
}
 